{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "uvicorn.fullname" . }}-app
  labels: {{- include "uvicorn.labels" . | nindent 4 }}
  # labels:
  #   type: local
spec:
  accessModes: 
  {{ toYaml .Values.persistence.accessModes  | indent 10 }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
{{- end -}}