apiVersion: v1
kind: Service
metadata:
  name: {{ include "uvicorn.fullname" . }}
  labels:
    {{- include "uvicorn.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portHttp }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portHttps }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "uvicorn.selectorLabels" . | nindent 4 }}
