pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:cdnagroup/cdnachart.git
          - cd cdnachart.git
          - echo -e "dockers \ncharts \nbitbucket-pipelines.yml \nCHART_BUILD \n" > github.gitignore
          - git push --mirror git@github.com:cdnagroup/helmchart.git