pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone git@bitbucket.org:cdnagroup/cdnachart.git
          - cd cdnachart
          - rm -rf charts
          - rm bitbucket-pipelines.yml
          - rm CHART_BUILD.MD
          - git remote add upstream git@github.com:cdnagroup/helmchart.git
          - git push upstream master --force
          - git push --tags upstream --force
          - git remote set-url origin git@github.com:cdnagroup/helmchart.git
          - git add .
          - git config --global user.email "cdnagroup@gmail.com"
          - git config --global user.name "CDNA IT Solution"
          - git commit -m "ignore"
          - git push --force