apiVersion: v1
kind: Service
metadata:
  name: {{ include "edms.fullname" . }}
  labels:
    {{- include "edms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "edms.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edms.fullname" . }}-redis
  labels:
    {{- include "edms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "edms.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edms.fullname" . }}-db
  labels:
    {{- include "edms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: pgsql
      protocol: TCP
      name: pgsql
  selector:
    {{- include "edms.selectorLabels" . | nindent 4 }}
