
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "fastapi.fullname" . }}-main.py
data:
{{- if .Values.python.main }}
  main.py: |-
{{ .Values.python.main | indent 4 }}
{{- end}}


{{- if .Values.python.requirements }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "fastapi.fullname" . }}-requirements.txt
data:
  requirements.txt: |-
{{ .Values.python.requirements| indent 4 }}
{{- end}}

{{- if .Values.python.start }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "fastapi.fullname" . }}-appStart.sh
data:
  appStart.sh: |-
{{ .Values.python.start | indent 4 }}
{{- end}}
